
# aliases
alias caracal_update='vagrant ssh -c "cd /var/www;sudo git pull origin"'
alias caracal_init_modules 'vagrant ssh -c "cd /var/www;sudo git submodule init;sudo git submodule update"'
alias cpass='PASSWORD_STORE_DIR=~/.password-store/Way2CU pass'
